kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{.Name}}
spec:
  repo: {{.Repo}}
  branch: {{.Branch}}
  helmSecretName: "helm-secret"
  targetNamespace: {{.TargetNamespace}}
  paths:
  - examples
