kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{.Name}}
spec:
  targetNamespace: {{.TargetNamespace}}
  repo: https://github.com/rancher/fleet-test-data
  branch: master
  paths:
  - bundle-diffs
